#:schema node_modules/wrangler/config-schema.json
name = "nourish"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# For Cloudflare Pages
pages_build_output_dir = ".open-next"
